apiVersion: v1
kind: Service
metadata:
  name: face-recognition-service
spec:
  selector:
    app: face-recognition
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30001
  type: NodePort
